name: Rails Tests and Code Critic

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.3'

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Run tests
      run: |
        rails db:migrate RAILS_ENV=test
        bundle exec rails test

    - name: Brakeman
      run: |
        bundle exec brakeman .

    - name: Rubocop
      run: |
        bundle exec rubocop .
